[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    User-Agent = "*"
    Allow = "/"
    Sitemap = "https://mspcollage-advance.netlify.app/sitemap.xml"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
