export const MATH_SYMBOLS = [
  { symbol: '±', name: 'Plus-Minus' },
  { symbol: '×', name: 'Multiplication' },
  { symbol: '÷', name: 'Division' },
  { symbol: '≠', name: 'Not Equal' },
  { symbol: '≈', name: 'Approximately' },
  { symbol: '∞', name: 'Infinity' },
  { symbol: '∑', name: 'Summation' },
  { symbol: '∫', name: 'Integral' },
  { symbol: '√', name: 'Square Root' },
  { symbol: '∏', name: 'Product' },
  { symbol: '∂', name: 'Partial Derivative' },
  { symbol: '∇', name: 'Nabla/Del' },
  { symbol: '∆', name: 'Delta/Change' },
  { symbol: '∈', name: 'Element Of' },
  { symbol: '∉', name: 'Not Element Of' },
  { symbol: '⊂', name: 'Subset Of' },
  { symbol: '⊃', name: 'Superset Of' },
  { symbol: '∪', name: 'Union' },
  { symbol: '∩', name: 'Intersection' },
  { symbol: '∀', name: 'For All' },
  { symbol: '∃', name: 'There Exists' },
  { symbol: '∄', name: 'Does Not Exist' },
  { symbol: '∅', name: 'Empty Set' },
  { symbol: '∝', name: 'Proportional To' },
  { symbol: '∞', name: 'Infinity' },
];

export const CHEMISTRY_SYMBOLS = [
  { symbol: 'H₂O', name: 'Water' },
  { symbol: 'CO₂', name: 'Carbon Dioxide' },
  { symbol: 'NaCl', name: 'Sodium Chloride' },
  { symbol: 'H₂SO₄', name: 'Sulfuric Acid' },
  { symbol: 'HCl', name: 'Hydrochloric Acid' },
  { symbol: 'NaOH', name: 'Sodium Hydroxide' },
  { symbol: 'CH₄', name: 'Methane' },
  { symbol: 'C₂H₅OH', name: 'Ethanol' },
  { symbol: 'NH₃', name: 'Ammonia' },
  { symbol: 'O₃', name: 'Ozone' },
  { symbol: 'CaCO₃', name: 'Calcium Carbonate' },
  { symbol: 'Fe₂O₃', name: 'Iron(III) Oxide' },
  { symbol: 'KMnO₄', name: 'Potassium Permanganate' },
  { symbol: 'AgNO₃', name: 'Silver Nitrate' },
  { symbol: '→', name: 'Reaction Arrow' },
  { symbol: '⇌', name: 'Equilibrium' },
  { symbol: 'Δ', name: 'Heat' },
  { symbol: '↑', name: 'Gas Evolution' },
  { symbol: '↓', name: 'Precipitation' },
  { symbol: '⇅', name: 'Resonance' },
];

export const PHYSICS_SYMBOLS = [
  { symbol: 'λ', name: 'Wavelength' },
  { symbol: 'μ', name: 'Micro' },
  { symbol: 'Ω', name: 'Ohm' },
  { symbol: 'π', name: 'Pi' },
  { symbol: 'θ', name: 'Theta' },
  { symbol: 'ρ', name: 'Density' },
  { symbol: 'σ', name: 'Sigma' },
  { symbol: 'τ', name: 'Tau' },
  { symbol: 'φ', name: 'Phi' },
  { symbol: 'ν', name: 'Frequency' },
  { symbol: 'α', name: 'Alpha' },
  { symbol: 'β', name: 'Beta' },
  { symbol: 'γ', name: 'Gamma' },
  { symbol: 'ε₀', name: 'Permittivity of Free Space' },
  { symbol: 'μ₀', name: 'Permeability of Free Space' },
  { symbol: '∆x', name: 'Displacement' },
  { symbol: '∆v', name: 'Change in Velocity' },
  { symbol: '∆t', name: 'Time Interval' },
  { symbol: '∆E', name: 'Change in Energy' },
  { symbol: '∆P', name: 'Change in Momentum' },
];

export const BIOLOGY_SYMBOLS = [
  { symbol: '♂', name: 'Male' },
  { symbol: '♀', name: 'Female' },
  { symbol: '→', name: 'Leads to' },
  { symbol: '⇌', name: 'Reversible Process' },
  { symbol: 'ATP', name: 'Adenosine Triphosphate' },
  { symbol: 'DNA', name: 'Deoxyribonucleic Acid' },
  { symbol: 'RNA', name: 'Ribonucleic Acid' },
  { symbol: 'ADP', name: 'Adenosine Diphosphate' },
  { symbol: 'NADH', name: 'Nicotinamide Adenine Dinucleotide' },
  { symbol: 'CO₂', name: 'Carbon Dioxide' },
  { symbol: 'O₂', name: 'Oxygen' },
  { symbol: 'H₂O', name: 'Water' },
  { symbol: 'C₆H₁₂O₆', name: 'Glucose' },
  { symbol: 'pH', name: 'pH Scale' },
  { symbol: '∆G', name: 'Change in Gibbs Free Energy' },
];

export const COMMON_FORMULAS = [
  { symbol: 'E=mc²', name: 'Mass-Energy Equivalence' },
  { symbol: 'F=ma', name: 'Newton\'s Second Law' },
  { symbol: 'PV=nRT', name: 'Ideal Gas Law' },
  { symbol: 'c=λν', name: 'Wave Speed' },
  { symbol: 'E=hν', name: 'Photon Energy' },
  { symbol: 'ΔG=ΔH-TΔS', name: 'Gibbs Free Energy' },
  { symbol: 'pH=-log[H⁺]', name: 'pH Definition' },
  { symbol: 'F=-kx', name: 'Hooke\'s Law' },
  { symbol: 'v=u+at', name: 'First Equation of Motion' },
  { symbol: 's=ut+½at²', name: 'Second Equation of Motion' },
  { symbol: 'v²=u²+2as', name: 'Third Equation of Motion' },
  { symbol: 'T=2π√(l/g)', name: 'Period of Simple Pendulum' },
  { symbol: 'V=IR', name: 'Ohm\'s Law' },
  { symbol: 'P=VI', name: 'Electric Power' },
  { symbol: 'F=GMm/r²', name: 'Gravitational Force' },
];

export const CONSTANTS = [
  { symbol: 'c = 3×10⁸ m/s', name: 'Speed of Light', unit: 'm/s' },
  { symbol: 'h = 6.626×10⁻³⁴', name: 'Planck Constant', unit: 'J·s' },
  { symbol: 'G = 6.674×10⁻¹¹', name: 'Gravitational Constant', unit: 'N·m²/kg²' },
  { symbol: 'NA = 6.022×10²³', name: 'Avogadro Number', unit: 'mol⁻¹' },
  { symbol: 'R = 8.314', name: 'Gas Constant', unit: 'J/(mol·K)' },
  { symbol: 'k = 1.381×10⁻²³', name: 'Boltzmann Constant', unit: 'J/K' },
  { symbol: 'e = 1.602×10⁻¹⁹', name: 'Elementary Charge', unit: 'C' },
  { symbol: 'me = 9.109×10⁻³¹', name: 'Electron Mass', unit: 'kg' },
  { symbol: 'mp = 1.672×10⁻²⁷', name: 'Proton Mass', unit: 'kg' },
  { symbol: 'ε₀ = 8.854×10⁻¹²', name: 'Vacuum Permittivity', unit: 'F/m' },
  { symbol: 'μ₀ = 4π×10⁻⁷', name: 'Vacuum Permeability', unit: 'H/m' },
  { symbol: 'g = 9.81', name: 'Acceleration due to Gravity', unit: 'm/s²' },
];

export const ADVANCED_MATH = [
  { symbol: '∮', name: 'Line Integral' },
  { symbol: '∯', name: 'Surface Integral' },
  { symbol: '∰', name: 'Volume Integral' },
  { symbol: '∇²', name: 'Laplacian' },
  { symbol: '∑∞ᵢ₌₁', name: 'Infinite Sum' },
  { symbol: '∏∞ᵢ₌₁', name: 'Infinite Product' },
  { symbol: 'lim x→∞', name: 'Limit to Infinity' },
  { symbol: '∫∞₀', name: 'Infinite Integral' },
  { symbol: '⟨x|ψ⟩', name: 'Bra-ket Notation' },
];

export const ADVANCED_PHYSICS = [
  { symbol: 'ψ(x,t)', name: 'Wave Function' },
  { symbol: 'Ĥψ = Eψ', name: 'Schrödinger Equation' },
  { symbol: 'E = ℏω', name: 'Photon Energy' },
  { symbol: 'p = ℏk', name: 'De Broglie Relation' },
  { symbol: 'F = -∇V', name: 'Conservative Force' },
  { symbol: '∇×E = -∂B/∂t', name: 'Faraday\'s Law' },
  { symbol: '∇×B = μ₀J + μ₀ε₀∂E/∂t', name: 'Ampere\'s Law' },
  { symbol: '∇·E = ρ/ε₀', name: 'Gauss\'s Law' },
  { symbol: '∇·B = 0', name: 'Gauss\'s Law for Magnetism' },
  { symbol: 'ds² = gᵢⱼdxᵢdxʲ', name: 'Metric Tensor' },
];

export const ADVANCED_CHEMISTRY = [
  { symbol: 'K = [C][D]/[A][B]', name: 'Equilibrium Constant' },
  { symbol: 'pH = -log[H⁺]', name: 'pH Definition' },
  { symbol: 'E = E° - (RT/nF)lnQ', name: 'Nernst Equation' },
  { symbol: 'ΔG° = -RTlnK', name: 'Standard Free Energy Change' },
  { symbol: 'k = Ae⁻ᴱᵃ/ᴿᵀ', name: 'Arrhenius Equation' },
  { symbol: 'PV = nRT', name: 'Ideal Gas Law' },
  { symbol: 'μ = -RTlna', name: 'Chemical Potential' },
  { symbol: 'dG = VdP - SdT', name: 'Gibbs Free Energy Differential' },
  { symbol: 'ΔH = ΔU + ΔnRT', name: 'Enthalpy Change' },
  { symbol: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O', name: 'Glucose Oxidation' },
];

export const ADVANCED_BIOLOGY = [
  { symbol: 'dN/dt = rN(1-N/K)', name: 'Logistic Growth' },
  { symbol: 'v = Vmax[S]/(Km+[S])', name: 'Michaelis-Menten Equation' },
  { symbol: 'ΔG = ΔH - TΔS', name: 'Gibbs Free Energy' },
  { symbol: 'P + ADP + Pi → ATP', name: 'ATP Synthesis' },
  { symbol: 'NADH + H⁺ + ½O₂ → NAD⁺ + H₂O', name: 'Electron Transport Chain' },
  { symbol: '2H₂O → O₂ + 4H⁺ + 4e⁻', name: 'Photolysis of Water' },
  { symbol: 'CO₂ + H₂O + energy → CH₂O + O₂', name: 'Photosynthesis' },
  { symbol: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy', name: 'Cellular Respiration' },
];

export const CONSTANT_SYMBOLS = [
  { symbol: '⁰', name: 'Superscript 0' },
  { symbol: '¹', name: 'Superscript 1' },
  { symbol: '²', name: 'Superscript 2' },
  { symbol: '³', name: 'Superscript 3' },
  { symbol: '⁴', name: 'Superscript 4' },
  { symbol: '⁵', name: 'Superscript 5' },
  { symbol: '⁶', name: 'Superscript 6' },
  { symbol: '⁷', name: 'Superscript 7' },
  { symbol: '⁸', name: 'Superscript 8' },
  { symbol: '⁹', name: 'Superscript 9' },
  { symbol: '⁻¹', name: 'Superscript -1' },
  { symbol: '⁻²', name: 'Superscript -2' },
  { symbol: '⁻³', name: 'Superscript -3' },
  { symbol: '⁻⁴', name: 'Superscript -4' },
  { symbol: '⁻⁵', name: 'Superscript -5' },
  { symbol: '⁻⁶', name: 'Superscript -6' },
  { symbol: '⁻⁷', name: 'Superscript -7' },
  { symbol: '⁻⁸', name: 'Superscript -8' },
  { symbol: '⁻⁹', name: 'Superscript -9' },
  { symbol: '⁺', name: 'Superscript Plus' },
  { symbol: '⁻', name: 'Superscript Minus' },
  { symbol: '⁽', name: 'Superscript Left Parenthesis' },
  { symbol: '⁾', name: 'Superscript Right Parenthesis' },
  { symbol: '₀', name: 'Subscript 0' },
  { symbol: '₁', name: 'Subscript 1' },
  { symbol: '₂', name: 'Subscript 2' },
  { symbol: '₃', name: 'Subscript 3' },
  { symbol: '₄', name: 'Subscript 4' },
  { symbol: '₅', name: 'Subscript 5' },
  { symbol: '₆', name: 'Subscript 6' },
  { symbol: '₇', name: 'Subscript 7' },
  { symbol: '₈', name: 'Subscript 8' },
  { symbol: '₉', name: 'Subscript 9' },
  { symbol: '₊', name: 'Subscript Plus' },
  { symbol: '₋', name: 'Subscript Minus' },
  { symbol: '₍', name: 'Subscript Left Parenthesis' },
  { symbol: '₎', name: 'Subscript Right Parenthesis' },
  { symbol: '()', name: 'Parentheses' },
  { symbol: '[]', name: 'Square Brackets' },
  { symbol: '{}', name: 'Curly Brackets' },
  { symbol: '⟨⟩', name: 'Angle Brackets' },
  { symbol: '|', name: 'Vertical Bar' },
  { symbol: '‖', name: 'Double Vertical Bar' },
  { symbol: '⌈⌉', name: 'Ceiling Brackets' },
  { symbol: '⌊⌋', name: 'Floor Brackets' },
  { symbol: '√', name: 'Square Root' },
  { symbol: '∛', name: 'Cube Root' },
  { symbol: '∜', name: 'Fourth Root' },
  { symbol: '∝', name: 'Proportional to' },
  { symbol: '∑', name: 'Summation' },
  { symbol: '∏', name: 'Product' },
  { symbol: '∫', name: 'Integral' },
  { symbol: '∆', name: 'Delta' },
  { symbol: '∇', name: 'Nabla' },
  { symbol: '∂', name: 'Partial Derivative' },
  { symbol: '∂²', name: 'Second Partial Derivative' },
  { symbol: '∂³', name: 'Third Partial Derivative' },
  { symbol: '∂⁴', name: 'Fourth Partial Derivative' },
  { symbol: '∂⁵', name: 'Fifth Partial Derivative' },
  { symbol: '∂⁶', name: 'Sixth Partial Derivative' },
  { symbol: '∂⁷', name: 'Seventh Partial Derivative' },
  { symbol: '∂⁸', name: 'Eighth Partial Derivative' },
  { symbol: '∂⁹', name: 'Ninth Partial Derivative' },
  { symbol: '∂¹⁰', name: 'Tenth Partial Derivative' },
  { symbol: '−', name: 'Minus Sign' },
  { symbol: '×', name: 'Multiplication Sign' },
  { symbol: '÷', name: 'Division Sign' },
  { symbol: '=', name: 'Equals Sign' },
  { symbol: '≠', name: 'Not Equal To' },
  { symbol: '<', name: 'Less Than' },
  { symbol: '>', name: 'Greater Than' },
  { symbol: '≤', name: 'Less Than or Equal To' },
  { symbol: '≥', name: 'Greater Than or Equal To' },
  { symbol: '≈', name: 'Approximately Equal To' },
  { symbol: '≡', name: 'Identical To' },
  { symbol: '∈', name: 'Element Of' },
  { symbol: '∉', name: 'Not an Element Of' },
  { symbol: '⊂', name: 'Subset Of' },
  { symbol: '⊃', name: 'Superset Of' },
  { symbol: '⊆', name: 'Subset or Equal To' },
  { symbol: '⊇', name: 'Superset or Equal To' },
  { symbol: '∪', name: 'Union' },
  { symbol: '∩', name: 'Intersection' },
  { symbol: '∅', name: 'Empty Set' },
  { symbol: '∀', name: 'For All' },
  { symbol: '∃', name: 'There Exists' },
  { symbol: '∄', name: 'There Does Not Exist' },
  { symbol: '∴', name: 'Therefore' },
  { symbol: '∵', name: 'Because' },
  { symbol: '∠', name: 'Angle' },
  { symbol: '⊥', name: 'Perpendicular To' },
  { symbol: '∥', name: 'Parallel To' },
  { symbol: '≅', name: 'Congruent To' },
  { symbol: '∼', name: 'Similar To' },
  { symbol: '→', name: 'Right Arrow' },
  { symbol: '←', name: 'Left Arrow' },
  { symbol: '↔', name: 'Left Right Arrow' },
  { symbol: '⇒', name: 'Implies' },
  { symbol: '⇔', name: 'If and Only If' },
  { symbol: '∑', name: 'Summation' },
  { symbol: '∏', name: 'Product' },
  { symbol: '∫', name: 'Integral' },
  { symbol: '∮', name: 'Contour Integral' },
  { symbol: '∞', name: 'Infinity' },
  { symbol: '!', name: 'Factorial' },
  { symbol: '%', name: 'Percent' },
  { symbol: '‰', name: 'Per Mille' },
  { symbol: '°', name: 'Degree' },
  { symbol: '′', name: 'Prime / Minute' },
  { symbol: '″', name: 'Double Prime / Second' },
  { symbol: '℃', name: 'Celsius' },
  { symbol: '℉', name: 'Fahrenheit' },
  { symbol: 'Ω', name: 'Ohm' },
  { symbol: 'µ', name: 'Micro Sign' },
  { symbol: 'Å', name: 'Angstrom' },
  { symbol: '№', name: 'Numero Sign' },
  { symbol: '℗', name: 'Sound Recording Copyright' },
  { symbol: '™', name: 'Trade Mark Sign' },
  { symbol: '℠', name: 'Service Mark Sign' },
  { symbol: '℮', name: 'Estimated Symbol' },
  { symbol: '℥', name: 'Ounce Sign' },
  { symbol: '℔', name: 'Pound Sign' },
  { symbol: '℞', name: 'Prescription Take' },
  { symbol: 'ℨ', name: 'Drachm Sign' },
  { symbol: '℩', name: 'Turned Greek Small Letter Iota' },
  { symbol: 'ℰ', name: 'Euler Constant' },
  { symbol: 'ℱ', name: 'Script Capital F' },
  { symbol: 'ℳ', name: 'Script Capital M' },
  { symbol: 'ℒ', name: 'Script Capital L' },
  { symbol: 'ℛ', name: 'Script Capital R' },
  { symbol: 'ℜ', name: 'Black-Letter Capital R' },
  { symbol: 'ℑ', name: 'Black-Letter Capital I' },
  { symbol: 'ℂ', name: 'Black-Letter Capital C' },
  { symbol: 'ℕ', name: 'Black-Letter Capital N' },
  { symbol: 'ℙ', name: 'Black-Letter Capital P' },
  { symbol: 'ℚ', name: 'Black-Letter Capital Q' },
  { symbol: 'ℝ', name: 'Black-Letter Capital R' },
  { symbol: 'ℤ', name: 'Black-Letter Capital Z' },
];