export const MATH_SYMBOLS = [
  { symbol: '±', name: 'Plus-Minus' },
  { symbol: '×', name: 'Multiplication' },
  { symbol: '÷', name: 'Division' },
  { symbol: '≠', name: 'Not Equal' },
  { symbol: '≈', name: 'Approximately' },
  { symbol: '∞', name: 'Infinity' },
  { symbol: '∑', name: 'Summation' },
  { symbol: '∫', name: 'Integral' },
  { symbol: '√', name: 'Square Root' },
  { symbol: '∏', name: 'Product' },
  { symbol: '∂', name: 'Partial Derivative' },
  { symbol: '∇', name: 'Nabla/Del' },
  { symbol: '∆', name: 'Delta/Change' },
  { symbol: '∈', name: 'Element Of' },
  { symbol: '∉', name: 'Not Element Of' },
  { symbol: '⊂', name: 'Subset Of' },
  { symbol: '⊃', name: 'Superset Of' },
  { symbol: '∪', name: 'Union' },
  { symbol: '∩', name: 'Intersection' },
  { symbol: '∀', name: 'For All' },
  { symbol: '∃', name: 'There Exists' },
  { symbol: '∄', name: 'Does Not Exist' },
  { symbol: '∅', name: 'Empty Set' },
  { symbol: '∝', name: 'Proportional To' },
  { symbol: '∞', name: 'Infinity' },
];

export const SUPERSCRIPT_NUMBERS = [
  { symbol: '⁰', name: 'Superscript 0' },
  { symbol: '¹', name: 'Superscript 1' },
  { symbol: '²', name: 'Superscript 2' },
  { symbol: '³', name: 'Superscript 3' },
  { symbol: '⁴', name: 'Superscript 4' },
  { symbol: '⁵', name: 'Superscript 5' },
  { symbol: '⁶', name: 'Superscript 6' },
  { symbol: '⁷', name: 'Superscript 7' },
  { symbol: '⁸', name: 'Superscript 8' },
  { symbol: '⁹', name: 'Superscript 9' },
];

export const SUBSCRIPT_NUMBERS = [
  { symbol: '₀', name: 'Subscript 0' },
  { symbol: '₁', name: 'Subscript 1' },
  { symbol: '₂', name: 'Subscript 2' },
  { symbol: '₃', name: 'Subscript 3' },
  { symbol: '₄', name: 'Subscript 4' },
  { symbol: '₅', name: 'Subscript 5' },
  { symbol: '₆', name: 'Subscript 6' },
  { symbol: '₇', name: 'Subscript 7' },
  { symbol: '₈', name: 'Subscript 8' },
  { symbol: '₉', name: 'Subscript 9' },
];

export const SUPERSCRIPT_LETTERS = [
  { symbol: 'ᵃ', name: 'Superscript a' },
  { symbol: 'ᵇ', name: 'Superscript b' },
  { symbol: 'ᶜ', name: 'Superscript c' },
  { symbol: 'ᵈ', name: 'Superscript d' },
  { symbol: 'ᵉ', name: 'Superscript e' },
  { symbol: 'ᶠ', name: 'Superscript f' },
  { symbol: 'ᵍ', name: 'Superscript g' },
  { symbol: 'ʰ', name: 'Superscript h' },
  { symbol: 'ⁱ', name: 'Superscript i' },
  { symbol: 'ʲ', name: 'Superscript j' },
  { symbol: 'ᵏ', name: 'Superscript k' },
  { symbol: 'ˡ', name: 'Superscript l' },
  { symbol: 'ᵐ', name: 'Superscript m' },
  { symbol: 'ⁿ', name: 'Superscript n' },
  { symbol: 'ᵒ', name: 'Superscript o' },
  { symbol: 'ᵖ', name: 'Superscript p' },
  { symbol: 'ʳ', name: 'Superscript r' },
  { symbol: 'ˢ', name: 'Superscript s' },
  { symbol: 'ᵗ', name: 'Superscript t' },
  { symbol: 'ᵘ', name: 'Superscript u' },
  { symbol: 'ᵛ', name: 'Superscript v' },
  { symbol: 'ʷ', name: 'Superscript w' },
  { symbol: 'ˣ', name: 'Superscript x' },
  { symbol: 'ʸ', name: 'Superscript y' },
  { symbol: 'ᶻ', name: 'Superscript z' },
  { symbol: 'ᴬ', name: 'Superscript A' },
  { symbol: 'ᴮ', name: 'Superscript B' },
  { symbol: 'ᴰ', name: 'Superscript D' },
  { symbol: 'ᴱ', name: 'Superscript E' },
  { symbol: 'ᴳ', name: 'Superscript G' },
  { symbol: 'ᴴ', name: 'Superscript H' },
  { symbol: 'ᴵ', name: 'Superscript I' },
  { symbol: 'ᴶ', name: 'Superscript J' },
  { symbol: 'ᴷ', name: 'Superscript K' },
  { symbol: 'ᴸ', name: 'Superscript L' },
  { symbol: 'ᴹ', name: 'Superscript M' },
  { symbol: 'ᴺ', name: 'Superscript N' },
  { symbol: 'ᴼ', name: 'Superscript O' },
  { symbol: 'ᴾ', name: 'Superscript P' },
  { symbol: 'ᴿ', name: 'Superscript R' },
  { symbol: 'ᵀ', name: 'Superscript T' },
  { symbol: 'ᵁ', name: 'Superscript U' },
  { symbol: 'ᵂ', name: 'Superscript W' },
  { symbol: 'ᵃ', name: 'Superscript X' },
  { symbol: 'ᵇ', name: 'Superscript Y' },
  { symbol: 'ᶜ', name: 'Superscript Z' },
  { symbol: 'ᵈ', name: 'Superscript A' },
  { symbol: 'ᵉ', name: 'Superscript B' },
  { symbol: 'ᶠ', name: 'Superscript D' },
  { symbol: 'ᵍ', name: 'Superscript E' },
  { symbol: 'ʰ', name: 'Superscript G' },
  { symbol: 'ⁱ', name: 'Superscript H' },
  { symbol: 'ʲ', name: 'Superscript I' },
  { symbol: 'ᵏ', name: 'Superscript J' },
  { symbol: 'ˡ', name: 'Superscript K' },
  { symbol: 'ᵐ', name: 'Superscript L' },
  { symbol: 'ⁿ', name: 'Superscript N' },
  { symbol: 'ᵒ', name: 'Superscript O' },
  { symbol: 'ᵖ', name: 'Superscript P' },
  { symbol: 'ʳ', name: 'Superscript R' },
  { symbol: 'ˢ', name: 'Superscript S' },
  { symbol: 'ᵗ', name: 'Superscript T' },
  { symbol: 'ᵘ', name: 'Superscript U' },
  { symbol: 'ᵛ', name: 'Superscript V' },
];

export const SUBSCRIPT_LETTERS = [
  { symbol: 'ₐ', name: 'Subscript a' },
  { symbol: 'ₑ', name: 'Subscript e' },
  { symbol: 'ₕ', name: 'Subscript h' },
  { symbol: 'ᵢ', name: 'Subscript i' },
  { symbol: 'ⱼ', name: 'Subscript j' },
  { symbol: 'ₖ', name: 'Subscript k' },
  { symbol: 'ₗ', name: 'Subscript l' },
  { symbol: 'ₘ', name: 'Subscript m' },
  { symbol: 'ₙ', name: 'Subscript n' },
  { symbol: 'ₒ', name: 'Subscript o' },
  { symbol: 'ₚ', name: 'Subscript p' },
  { symbol: 'ᵣ', name: 'Subscript r' },
  { symbol: 'ₛ', name: 'Subscript s' },
  { symbol: 'ₜ', name: 'Subscript t' },
  { symbol: 'ᵤ', name: 'Subscript u' },
  { symbol: 'ᵥ', name: 'Subscript v' },
  { symbol: 'ₓ', name: 'Subscript x' },
  { symbol: 'ᵦ', name: 'Subscript w' },
  { symbol: 'ᵧ', name: 'Subscript y' },
  { symbol: 'ᵨ', name: 'Subscript z' },
  { symbol: 'ⱼ', name: 'Subscript j' },
  { symbol: 'ₚ', name: 'Subscript p' },
  { symbol: 'ᵣ', name: 'Subscript r' },
  { symbol: 'ₛ', name: 'Subscript s' },
  { symbol: 'ₜ', name: 'Subscript t' },
  { symbol: 'ᵤ', name: 'Subscript u' },
  { symbol: 'ᵥ', name: 'Subscript v' },
  { symbol: 'ₓ', name: 'Subscript x' },
  { symbol: 'ᵧ', name: 'Subscript y' },
  { symbol: 'ᵨ', name: 'Subscript z' },
  { symbol: 'ⱼ', name: 'Subscript j' },

];

export const CHEMISTRY_SYMBOLS = [
  { symbol: 'H₂O', name: 'Water' },
  { symbol: 'CO₂', name: 'Carbon Dioxide' },
  { symbol: 'NaCl', name: 'Sodium Chloride' },
  { symbol: 'H₂SO₄', name: 'Sulfuric Acid' },
  { symbol: 'HCl', name: 'Hydrochloric Acid' },
  { symbol: 'NaOH', name: 'Sodium Hydroxide' },
  { symbol: 'CH₄', name: 'Methane' },
  { symbol: 'C₂H₅OH', name: 'Ethanol' },
  { symbol: 'NH₃', name: 'Ammonia' },
  { symbol: 'O₃', name: 'Ozone' },
  { symbol: 'CaCO₃', name: 'Calcium Carbonate' },
  { symbol: 'Fe₂O₃', name: 'Iron(III) Oxide' },
  { symbol: 'KMnO₄', name: 'Potassium Permanganate' },
  { symbol: 'AgNO₃', name: 'Silver Nitrate' },
  { symbol: '→', name: 'Reaction Arrow' },
  { symbol: '⇌', name: 'Equilibrium' },
  { symbol: 'Δ', name: 'Heat' },
  { symbol: '↑', name: 'Gas Evolution' },
  { symbol: '↓', name: 'Precipitation' },
  { symbol: '⇅', name: 'Resonance' },
];

export const PHYSICS_SYMBOLS = [
  { symbol: 'λ', name: 'Wavelength' },
  { symbol: 'μ', name: 'Micro' },
  { symbol: 'Ω', name: 'Ohm' },
  { symbol: 'π', name: 'Pi' },
  { symbol: 'θ', name: 'Theta' },
  { symbol: 'ρ', name: 'Density' },
  { symbol: 'σ', name: 'Sigma' },
  { symbol: 'τ', name: 'Tau' },
  { symbol: 'φ', name: 'Phi' },
  { symbol: 'ν', name: 'Frequency' },
  { symbol: 'α', name: 'Alpha' },
  { symbol: 'β', name: 'Beta' },
  { symbol: 'γ', name: 'Gamma' },
  { symbol: 'ε₀', name: 'Permittivity of Free Space' },
  { symbol: 'μ₀', name: 'Permeability of Free Space' },
  { symbol: '∆x', name: 'Displacement' },
  { symbol: '∆v', name: 'Change in Velocity' },
  { symbol: '∆t', name: 'Time Interval' },
  { symbol: '∆E', name: 'Change in Energy' },
  { symbol: '∆P', name: 'Change in Momentum' },
];

export const BIOLOGY_SYMBOLS = [
  { symbol: '♂', name: 'Male' },
  { symbol: '♀', name: 'Female' },
  { symbol: '→', name: 'Leads to' },
  { symbol: '⇌', name: 'Reversible Process' },
  { symbol: 'ATP', name: 'Adenosine Triphosphate' },
  { symbol: 'DNA', name: 'Deoxyribonucleic Acid' },
  { symbol: 'RNA', name: 'Ribonucleic Acid' },
  { symbol: 'ADP', name: 'Adenosine Diphosphate' },
  { symbol: 'NADH', name: 'Nicotinamide Adenine Dinucleotide' },
  { symbol: 'CO₂', name: 'Carbon Dioxide' },
  { symbol: 'O₂', name: 'Oxygen' },
  { symbol: 'H₂O', name: 'Water' },
  { symbol: 'C₆H₁₂O₆', name: 'Glucose' },
  { symbol: 'pH', name: 'pH Scale' },
  { symbol: '∆G', name: 'Change in Gibbs Free Energy' },
];

export const COMMON_FORMULAS = [
  { symbol: 'E=mc²', name: 'Mass-Energy Equivalence' },
  { symbol: 'F=ma', name: 'Newton\'s Second Law' },
  { symbol: 'PV=nRT', name: 'Ideal Gas Law' },
  { symbol: 'c=λν', name: 'Wave Speed' },
  { symbol: 'E=hν', name: 'Photon Energy' },
  { symbol: 'ΔG=ΔH-TΔS', name: 'Gibbs Free Energy' },
  { symbol: 'pH=-log[H⁺]', name: 'pH Definition' },
  { symbol: 'F=-kx', name: 'Hooke\'s Law' },
  { symbol: 'v=u+at', name: 'First Equation of Motion' },
  { symbol: 's=ut+½at²', name: 'Second Equation of Motion' },
  { symbol: 'v²=u²+2as', name: 'Third Equation of Motion' },
  { symbol: 'T=2π√(l/g)', name: 'Period of Simple Pendulum' },
  { symbol: 'V=IR', name: 'Ohm\'s Law' },
  { symbol: 'P=VI', name: 'Electric Power' },
  { symbol: 'F=GMm/r²', name: 'Gravitational Force' },
];

export const CONSTANTS = [
  { symbol: 'c = 3×10⁸ m/s', name: 'Speed of Light', unit: 'm/s' },
  { symbol: 'h = 6.626×10⁻³⁴', name: 'Planck Constant', unit: 'J·s' },
  { symbol: 'G = 6.674×10⁻¹¹', name: 'Gravitational Constant', unit: 'N·m²/kg²' },
  { symbol: 'NA = 6.022×10²³', name: 'Avogadro Number', unit: 'mol⁻¹' },
  { symbol: 'R = 8.314', name: 'Gas Constant', unit: 'J/(mol·K)' },
  { symbol: 'k = 1.381×10⁻²³', name: 'Boltzmann Constant', unit: 'J/K' },
  { symbol: 'e = 1.602×10⁻¹⁹', name: 'Elementary Charge', unit: 'C' },
  { symbol: 'me = 9.109×10⁻³¹', name: 'Electron Mass', unit: 'kg' },
  { symbol: 'mp = 1.672×10⁻²⁷', name: 'Proton Mass', unit: 'kg' },
  { symbol: 'ε₀ = 8.854×10⁻¹²', name: 'Vacuum Permittivity', unit: 'F/m' },
  { symbol: 'μ₀ = 4π×10⁻⁷', name: 'Vacuum Permeability', unit: 'H/m' },
  { symbol: 'g = 9.81', name: 'Acceleration due to Gravity', unit: 'm/s²' },
];

export const ADVANCED_MATH = [
  { symbol: '∮', name: 'Line Integral' },
  { symbol: '∯', name: 'Surface Integral' },
  { symbol: '∰', name: 'Volume Integral' },
  { symbol: '∇²', name: 'Laplacian' },
  { symbol: '∑∞ᵢ₌₁', name: 'Infinite Sum' },
  { symbol: '∏∞ᵢ₌₁', name: 'Infinite Product' },
  { symbol: 'lim x→∞', name: 'Limit to Infinity' },
  { symbol: '∫∞₀', name: 'Infinite Integral' },
  { symbol: '⟨x|ψ⟩', name: 'Bra-ket Notation' },
];

export const ADVANCED_PHYSICS = [
  { symbol: 'ψ(x,t)', name: 'Wave Function' },
  { symbol: 'Ĥψ = Eψ', name: 'Schrödinger Equation' },
  { symbol: 'E = ℏω', name: 'Photon Energy' },
  { symbol: 'p = ℏk', name: 'De Broglie Relation' },
  { symbol: 'F = -∇V', name: 'Conservative Force' },
  { symbol: '∇×E = -∂B/∂t', name: 'Faraday\'s Law' },
  { symbol: '∇×B = μ₀J + μ₀ε₀∂E/∂t', name: 'Ampere\'s Law' },
  { symbol: '∇·E = ρ/ε₀', name: 'Gauss\'s Law' },
  { symbol: '∇·B = 0', name: 'Gauss\'s Law for Magnetism' },
  { symbol: 'ds² = gᵢⱼdxᵢdxʲ', name: 'Metric Tensor' },
];

export const ADVANCED_CHEMISTRY = [
  { symbol: 'K = [C][D]/[A][B]', name: 'Equilibrium Constant' },
  { symbol: 'pH = -log[H⁺]', name: 'pH Definition' },
  { symbol: 'E = E° - (RT/nF)lnQ', name: 'Nernst Equation' },
  { symbol: 'ΔG° = -RTlnK', name: 'Standard Free Energy Change' },
  { symbol: 'k = Ae⁻ᴱᵃ/ᴿᵀ', name: 'Arrhenius Equation' },
  { symbol: 'PV = nRT', name: 'Ideal Gas Law' },
  { symbol: 'μ = -RTlna', name: 'Chemical Potential' },
  { symbol: 'dG = VdP - SdT', name: 'Gibbs Free Energy Differential' },
  { symbol: 'ΔH = ΔU + ΔnRT', name: 'Enthalpy Change' },
  { symbol: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O', name: 'Glucose Oxidation' },
];

export const ADVANCED_BIOLOGY = [
  { symbol: 'dN/dt = rN(1-N/K)', name: 'Logistic Growth' },
  { symbol: 'v = Vmax[S]/(Km+[S])', name: 'Michaelis-Menten Equation' },
  { symbol: 'ΔG = ΔH - TΔS', name: 'Gibbs Free Energy' },
  { symbol: 'P + ADP + Pi → ATP', name: 'ATP Synthesis' },
  { symbol: 'NADH + H⁺ + ½O₂ → NAD⁺ + H₂O', name: 'Electron Transport Chain' },
  { symbol: '2H₂O → O₂ + 4H⁺ + 4e⁻', name: 'Photolysis of Water' },
  { symbol: 'CO₂ + H₂O + energy → CH₂O + O₂', name: 'Photosynthesis' },
  { symbol: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy', name: 'Cellular Respiration' },
];

export const GREEK_SYMBOLS = [
  { symbol: 'Α', name: 'Alpha (Uppercase)' },
  { symbol: 'Β', name: 'Beta (Uppercase)' },
  { symbol: 'Γ', name: 'Gamma (Uppercase)' },
  { symbol: 'Δ', name: 'Delta (Uppercase)' },
  { symbol: 'Ε', name: 'Epsilon (Uppercase)' },
  { symbol: 'Ζ', name: 'Zeta (Uppercase)' },
  { symbol: 'Η', name: 'Eta (Uppercase)' },
  { symbol: 'Θ', name: 'Theta (Uppercase)' },
  { symbol: 'Ι', name: 'Iota (Uppercase)' },
  { symbol: 'Κ', name: 'Kappa (Uppercase)' },
  { symbol: 'Λ', name: 'Lambda (Uppercase)' },
  { symbol: 'Μ', name: 'Mu (Uppercase)' },
  { symbol: 'Ν', name: 'Nu (Uppercase)' },
  { symbol: 'Ξ', name: 'Xi (Uppercase)' },
  { symbol: 'Ο', name: 'Omicron (Uppercase)' },
  { symbol: 'Π', name: 'Pi (Uppercase)' },
  { symbol: 'Ρ', name: 'Rho (Uppercase)' },
  { symbol: 'Σ', name: 'Sigma (Uppercase)' },
  { symbol: 'Τ', name: 'Tau (Uppercase)' },
  { symbol: 'Υ', name: 'Upsilon (Uppercase)' },
  { symbol: 'Φ', name: 'Phi (Uppercase)' },
  { symbol: 'Χ', name: 'Chi (Uppercase)' },
  { symbol: 'Ψ', name: 'Psi (Uppercase)' },
  { symbol: 'Ω', name: 'Omega (Uppercase)' },
  { symbol: 'α', name: 'Alpha (Lowercase)' },
  { symbol: 'β', name: 'Beta (Lowercase)' },
  { symbol: 'γ', name: 'Gamma (Lowercase)' },
  { symbol: 'δ', name: 'Delta (Lowercase)' },
  { symbol: 'ε', name: 'Epsilon (Lowercase)' },
  { symbol: 'ζ', name: 'Zeta (Lowercase)' },
  { symbol: 'η', name: 'Eta (Lowercase)' },
  { symbol: 'θ', name: 'Theta (Lowercase)' },
  { symbol: 'ι', name: 'Iota (Lowercase)' },
  { symbol: 'κ', name: 'Kappa (Lowercase)' },
  { symbol: 'λ', name: 'Lambda (Lowercase)' },
  { symbol: 'μ', name: 'Mu (Lowercase)' },
  { symbol: 'ν', name: 'Nu (Lowercase)' },
  { symbol: 'ξ', name: 'Xi (Lowercase)' },
  { symbol: 'ο', name: 'Omicron (Lowercase)' },
  { symbol: 'π', name: 'Pi (Lowercase)' },
  { symbol: 'ρ', name: 'Rho (Lowercase)' },
  { symbol: 'σ', name: 'Sigma (Lowercase)' },
  { symbol: 'τ', name: 'Tau (Lowercase)' },
  { symbol: 'υ', name: 'Upsilon (Lowercase)' },
  { symbol: 'φ', name: 'Phi (Lowercase)' },
  { symbol: 'χ', name: 'Chi (Lowercase)' },
  { symbol: 'ψ', name: 'Psi (Lowercase)' },
  { symbol: 'ω', name: 'Omega (Lowercase)' },
];

export const CONSTANT_SYMBOLS = [
  { symbol: '⁰', name: 'Superscript 0' },
  { symbol: '¹', name: 'Superscript 1' },
  { symbol: '²', name: 'Superscript 2' },
  { symbol: '³', name: 'Superscript 3' },
  { symbol: '⁴', name: 'Superscript 4' },
  { symbol: '⁵', name: 'Superscript 5' },
  { symbol: '⁶', name: 'Superscript 6' },
  { symbol: '⁷', name: 'Superscript 7' },
  { symbol: '⁸', name: 'Superscript 8' },
  { symbol: '⁹', name: 'Superscript 9' },
  { symbol: '⁻¹', name: 'Superscript -1' },
  { symbol: '⁻²', name: 'Superscript -2' },
  { symbol: '⁻³', name: 'Superscript -3' },
  { symbol: '⁻⁴', name: 'Superscript -4' },
  { symbol: '⁻⁵', name: 'Superscript -5' },
  { symbol: '⁻⁶', name: 'Superscript -6' },
  { symbol: '⁻⁷', name: 'Superscript -7' },
  { symbol: '⁻⁸', name: 'Superscript -8' },
  { symbol: '⁻⁹', name: 'Superscript -9' },
  { symbol: '⁺', name: 'Superscript Plus' },
  { symbol: '⁻', name: 'Superscript Minus' },
  { symbol: '⁽', name: 'Superscript Left Parenthesis' },
  { symbol: '⁾', name: 'Superscript Right Parenthesis' },
  { symbol: '₀', name: 'Subscript 0' },
  { symbol: '₁', name: 'Subscript 1' },
  { symbol: '₂', name: 'Subscript 2' },
  { symbol: '₃', name: 'Subscript 3' },
  { symbol: '₄', name: 'Subscript 4' },
  { symbol: '₅', name: 'Subscript 5' },
  { symbol: '₆', name: 'Subscript 6' },
  { symbol: '₇', name: 'Subscript 7' },
  { symbol: '₈', name: 'Subscript 8' },
  { symbol: '₉', name: 'Subscript 9' },
  { symbol: '₊', name: 'Subscript Plus' },
  { symbol: '₋', name: 'Subscript Minus' },
  { symbol: '₍', name: 'Subscript Left Parenthesis' },
  { symbol: '₎', name: 'Subscript Right Parenthesis' },
  { symbol: '()', name: 'Parentheses' },
  { symbol: '[]', name: 'Square Brackets' },
  { symbol: '{}', name: 'Curly Brackets' },
  { symbol: '⟨⟩', name: 'Angle Brackets' },
  { symbol: '|', name: 'Vertical Bar' },
  { symbol: '‖', name: 'Double Vertical Bar' },
  { symbol: '⌈⌉', name: 'Ceiling Brackets' },
  { symbol: '⌊⌋', name: 'Floor Brackets' },
  { symbol: '√', name: 'Square Root' },
  { symbol: '∛', name: 'Cube Root' },
  { symbol: '∜', name: 'Fourth Root' },
  { symbol: '∝', name: 'Proportional to' },
  { symbol: '∑', name: 'Summation' },
  { symbol: '∏', name: 'Product' },
  { symbol: '∫', name: 'Integral' },
  { symbol: '∆', name: 'Delta' },
  { symbol: '∇', name: 'Nabla' },
  { symbol: '∂', name: 'Partial Derivative' },
  { symbol: '∂²', name: 'Second Partial Derivative' },
  { symbol: '∂³', name: 'Third Partial Derivative' },
  { symbol: '∂⁴', name: 'Fourth Partial Derivative' },
  { symbol: '∂⁵', name: 'Fifth Partial Derivative' },
  { symbol: '∂⁶', name: 'Sixth Partial Derivative' },
  { symbol: '∂⁷', name: 'Seventh Partial Derivative' },
  { symbol: '∂⁸', name: 'Eighth Partial Derivative' },
  { symbol: '∂⁹', name: 'Ninth Partial Derivative' },
  { symbol: '∂¹⁰', name: 'Tenth Partial Derivative' },
  { symbol: '−', name: 'Minus Sign' },
  { symbol: '×', name: 'Multiplication Sign' },
  { symbol: '÷', name: 'Division Sign' },
  { symbol: '=', name: 'Equals Sign' },
  { symbol: '≠', name: 'Not Equal To' },
  { symbol: '<', name: 'Less Than' },
  { symbol: '>', name: 'Greater Than' },
  { symbol: '≤', name: 'Less Than or Equal To' },
  { symbol: '≥', name: 'Greater Than or Equal To' },
  { symbol: '≈', name: 'Approximately Equal To' },
  { symbol: '≡', name: 'Identical To' },
  { symbol: '∈', name: 'Element Of' },
  { symbol: '∉', name: 'Not an Element Of' },
  { symbol: '⊂', name: 'Subset Of' },
  { symbol: '⊃', name: 'Superset Of' },
  { symbol: '⊆', name: 'Subset or Equal To' },
  { symbol: '⊇', name: 'Superset or Equal To' },
  { symbol: '∪', name: 'Union' },
  { symbol: '∩', name: 'Intersection' },
  { symbol: '∅', name: 'Empty Set' },
  { symbol: '∀', name: 'For All' },
  { symbol: '∃', name: 'There Exists' },
  { symbol: '∄', name: 'There Does Not Exist' },
  { symbol: '∴', name: 'Therefore' },
  { symbol: '∵', name: 'Because' },
  { symbol: '∠', name: 'Angle' },
  { symbol: '⊥', name: 'Perpendicular To' },
  { symbol: '∥', name: 'Parallel To' },
  { symbol: '≅', name: 'Congruent To' },
  { symbol: '∼', name: 'Similar To' },
  { symbol: '→', name: 'Right Arrow' },
  { symbol: '←', name: 'Left Arrow' },
  { symbol: '↔', name: 'Left Right Arrow' },
  { symbol: '⇒', name: 'Implies' },
  { symbol: '⇔', name: 'If and Only If' },
  { symbol: '∑', name: 'Summation' },
  { symbol: '∏', name: 'Product' },
  { symbol: '∫', name: 'Integral' },
  { symbol: '∮', name: 'Contour Integral' },
  { symbol: '∞', name: 'Infinity' },
  { symbol: '!', name: 'Factorial' },
  { symbol: '%', name: 'Percent' },
  { symbol: '‰', name: 'Per Mille' },
  { symbol: '°', name: 'Degree' },
  { symbol: '′', name: 'Prime / Minute' },
  { symbol: '″', name: 'Double Prime / Second' },
  { symbol: '℃', name: 'Celsius' },
  { symbol: '℉', name: 'Fahrenheit' },
  { symbol: 'Ω', name: 'Ohm' },
  { symbol: 'µ', name: 'Micro Sign' },
  { symbol: 'Å', name: 'Angstrom' },
  { symbol: '№', name: 'Numero Sign' },
  { symbol: '℗', name: 'Sound Recording Copyright' },
  { symbol: '™', name: 'Trade Mark Sign' },
  { symbol: '℠', name: 'Service Mark Sign' },
  { symbol: '℮', name: 'Estimated Symbol' },
  { symbol: '℥', name: 'Ounce Sign' },
  { symbol: '℔', name: 'Pound Sign' },
  { symbol: '℞', name: 'Prescription Take' },
  { symbol: 'ℨ', name: 'Drachm Sign' },
  { symbol: '℩', name: 'Turned Greek Small Letter Iota' },
  { symbol: 'ℰ', name: 'Euler Constant' },
  { symbol: 'ℱ', name: 'Script Capital F' },
  { symbol: 'ℳ', name: 'Script Capital M' },
  { symbol: 'ℒ', name: 'Script Capital L' },
  { symbol: 'ℛ', name: 'Script Capital R' },
  { symbol: 'ℜ', name: 'Black-Letter Capital R' },
  { symbol: 'ℑ', name: 'Black-Letter Capital I' },
  { symbol: 'ℂ', name: 'Black-Letter Capital C' },
  { symbol: 'ℕ', name: 'Black-Letter Capital N' },
  { symbol: 'ℙ', name: 'Black-Letter Capital P' },
  { symbol: 'ℚ', name: 'Black-Letter Capital Q' },
  { symbol: 'ℝ', name: 'Black-Letter Capital R' },
  { symbol: 'ℤ', name: 'Black-Letter Capital Z' },
];